const pool = require('../config/database');

const MIN_COMMISSION_RATE = 0.05;

const getCommissionRate = () => {
  const parsed = parseFloat(process.env.PLATFORM_COMMISSION_RATE || '0.05');
  if (Number.isNaN(parsed)) return MIN_COMMISSION_RATE;
  return Math.max(MIN_COMMISSION_RATE, parsed);
};

const getPeriodMonth = (dateInput = new Date()) => {
  const date = dateInput instanceof Date ? dateInput : new Date(dateInput);
  if (Number.isNaN(date.getTime())) return getPeriodMonth(new Date());
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
};

const ENSURE_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS platform_commissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  source_type VARCHAR(30) NOT NULL CHECK (source_type IN ('booking_payment', 'product_order')),
  source_id INTEGER NOT NULL,
  gross_amount NUMERIC(12,2) NOT NULL,
  commission_rate NUMERIC(5,4) NOT NULL,
  commission_amount NUMERIC(12,2) NOT NULL,
  period_month CHAR(7) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (source_type, source_id)
);
CREATE INDEX IF NOT EXISTS idx_platform_commissions_tenant_id ON platform_commissions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_platform_commissions_period_month ON platform_commissions(period_month);
`;

let tableReady = false;

const ensurePlatformCommissionsTable = async () => {
  if (tableReady) return;
  await pool.query(ENSURE_TABLE_SQL);
  tableReady = true;
};

const recordCommission = async ({
  tenantId,
  sourceType,
  sourceId,
  grossAmount,
  saleDate,
}) => {
  await ensurePlatformCommissionsTable();

  const gross = parseFloat(grossAmount);
  if (!tenantId || !sourceId || !gross || gross <= 0) {
    return { skipped: true, reason: 'invalid_input' };
  }

  const rate = getCommissionRate();
  const commissionAmount = Math.round(gross * rate * 100) / 100;
  const periodMonth = getPeriodMonth(saleDate || new Date());

  const [existing] = await pool.query(
    'SELECT id FROM platform_commissions WHERE source_type = ? AND source_id = ?',
    [sourceType, sourceId]
  );
  if (existing.length) return { skipped: true, reason: 'already_recorded' };

  const [result] = await pool.query(
    `INSERT INTO platform_commissions
      (tenant_id, source_type, source_id, gross_amount, commission_rate, commission_amount, period_month)
     VALUES (?, ?, ?, ?, ?, ?, ?)`,
    [tenantId, sourceType, sourceId, gross, rate, commissionAmount, periodMonth]
  );

  return {
    id: result.insertId,
    commissionAmount,
    periodMonth,
    rate,
  };
};

const recordBookingPaymentCommission = async (payment) => {
  if (!payment?.id || !payment?.tenant_id) return { skipped: true };
  return recordCommission({
    tenantId: payment.tenant_id,
    sourceType: 'booking_payment',
    sourceId: payment.id,
    grossAmount: payment.amount,
    saleDate: payment.confirmed_at || payment.created_at,
  });
};

const recordProductOrderCommission = async (order) => {
  if (!order?.id || !order?.tenant_id) return { skipped: true };
  return recordCommission({
    tenantId: order.tenant_id,
    sourceType: 'product_order',
    sourceId: order.id,
    grossAmount: order.total_amount,
    saleDate: order.confirmed_at || order.updated_at || order.created_at,
  });
};

const recordProductOrderGroupCommissions = async (orderGroupId) => {
  const [orders] = await pool.query(
    `SELECT * FROM product_orders WHERE order_group_id = ? AND status IN ('paid', 'delivered')`,
    [orderGroupId]
  );
  const results = [];
  for (const order of orders) {
    results.push(await recordProductOrderCommission(order));
  }
  return results;
};

const getCurrentPeriodMonth = () => getPeriodMonth(new Date());

/** Confirmed tenant sales from bookings + marketplace (source of truth for gross sales). */
const getTenantSalesTotals = async ({ tenantId, periodMonth } = {}) => {
  const paymentParams = [];
  const orderParams = [];
  let paymentWhere = "p.status IN ('successful', 'confirmed')";
  let orderWhere = "po.status IN ('paid', 'delivered')";

  if (tenantId) {
    paymentWhere += ' AND p.tenant_id = ?';
    orderParams.push(tenantId);
    paymentParams.push(tenantId);
    orderWhere += ' AND po.tenant_id = ?';
  }

  if (periodMonth) {
    paymentWhere += " AND to_char(COALESCE(p.confirmed_at, p.created_at), 'YYYY-MM') = ?";
    paymentParams.push(periodMonth);
    orderWhere += " AND to_char(COALESCE(po.confirmed_at, po.updated_at, po.created_at), 'YYYY-MM') = ?";
    orderParams.push(periodMonth);
  }

  const [[paymentRow]] = await pool.query(
    `SELECT COALESCE(SUM(p.amount), 0) AS total FROM payments p WHERE ${paymentWhere}`,
    paymentParams
  );
  const [[orderRow]] = await pool.query(
    `SELECT COALESCE(SUM(po.total_amount), 0) AS total FROM product_orders po WHERE ${orderWhere}`,
    orderParams
  );

  const bookingSales = parseFloat(paymentRow?.total || 0);
  const productSales = parseFloat(orderRow?.total || 0);
  return {
    periodMonth: periodMonth || null,
    bookingSales,
    productSales,
    totalSales: Math.round((bookingSales + productSales) * 100) / 100,
  };
};

const getAllTimePlatformEarnings = async () => {
  await ensurePlatformCommissionsTable();
  const [[row]] = await pool.query(
    'SELECT COALESCE(SUM(commission_amount), 0) AS total FROM platform_commissions'
  );
  return parseFloat(row?.total || 0);
};

const getPlatformCommissionTotals = async (periodMonth = getCurrentPeriodMonth()) => {
  await ensurePlatformCommissionsTable();
  const sales = await getTenantSalesTotals({ periodMonth });
  const [[totals]] = await pool.query(
    `SELECT
      COALESCE(SUM(commission_amount), 0) AS platform_commission,
      COUNT(*) AS transaction_count
     FROM platform_commissions
     WHERE period_month = ?`,
    [periodMonth]
  );
  const rate = getCommissionRate();
  const recordedCommission = parseFloat(totals.platform_commission || 0);
  const expectedCommission = Math.round(sales.totalSales * rate * 100) / 100;
  return {
    periodMonth,
    commissionRate: rate,
    grossSales: sales.totalSales,
    bookingSales: sales.bookingSales,
    productSales: sales.productSales,
    platformCommission: recordedCommission > 0 ? recordedCommission : expectedCommission,
    transactionCount: parseInt(totals.transaction_count || 0, 10),
  };
};

const getTenantCommissionStats = async (tenantId, periodMonth = getCurrentPeriodMonth()) => {
  await ensurePlatformCommissionsTable();
  const sales = await getTenantSalesTotals({ tenantId, periodMonth });
  const rate = getCommissionRate();
  const [[stats]] = await pool.query(
    `SELECT COALESCE(SUM(commission_amount), 0) AS platform_commission
     FROM platform_commissions
     WHERE tenant_id = ? AND period_month = ?`,
    [tenantId, periodMonth]
  );
  const recordedCommission = parseFloat(stats.platform_commission || 0);
  const platformCommission = recordedCommission > 0
    ? recordedCommission
    : Math.round(sales.totalSales * rate * 100) / 100;
  return {
    periodMonth,
    commissionRate: rate,
    grossSales: sales.totalSales,
    bookingSales: sales.bookingSales,
    productSales: sales.productSales,
    platformCommission,
    netEarnings: Math.round((sales.totalSales - platformCommission) * 100) / 100,
  };
};

const getMonthlyCommissionByTenant = async (periodMonth = getCurrentPeriodMonth()) => {
  await ensurePlatformCommissionsTable();
  const [rows] = await pool.query(
    `SELECT pc.tenant_id,
      c.company_name,
      t.email,
      COALESCE(SUM(pc.commission_amount), 0) AS platform_commission,
      COUNT(*) AS transaction_count
     FROM platform_commissions pc
     JOIN tenants t ON pc.tenant_id = t.id
     LEFT JOIN companies c ON c.tenant_id = t.id
     WHERE pc.period_month = ?
     GROUP BY pc.tenant_id, c.company_name, t.email
     ORDER BY platform_commission DESC`,
    [periodMonth]
  );

  const rate = getCommissionRate();
  const enriched = await Promise.all(rows.map(async (row) => {
    const sales = await getTenantSalesTotals({ tenantId: row.tenant_id, periodMonth });
    const recorded = parseFloat(row.platform_commission || 0);
    return {
      ...row,
      gross_sales: sales.totalSales,
      platform_commission: recorded > 0 ? recorded : Math.round(sales.totalSales * rate * 100) / 100,
      transaction_count: parseInt(row.transaction_count || 0, 10),
    };
  }));
  return enriched;
};

const getCommissionHistory = async (limitMonths = 12) => {
  await ensurePlatformCommissionsTable();
  const [rows] = await pool.query(
    `SELECT period_month,
      COALESCE(SUM(commission_amount), 0) AS platform_commission,
      COUNT(*) AS transaction_count
     FROM platform_commissions
     GROUP BY period_month
     ORDER BY period_month DESC
     LIMIT ?`,
    [limitMonths]
  );

  const history = [];
  for (const row of rows) {
    const sales = await getTenantSalesTotals({ periodMonth: row.period_month });
    const rate = getCommissionRate();
    const recorded = parseFloat(row.platform_commission || 0);
    history.push({
      period_month: row.period_month,
      gross_sales: sales.totalSales,
      platform_commission: recorded > 0 ? recorded : Math.round(sales.totalSales * rate * 100) / 100,
      transaction_count: parseInt(row.transaction_count || 0, 10),
    });
  }
  return history;
};

module.exports = {
  MIN_COMMISSION_RATE,
  getCommissionRate,
  getPeriodMonth,
  getCurrentPeriodMonth,
  ensurePlatformCommissionsTable,
  recordCommission,
  recordBookingPaymentCommission,
  recordProductOrderCommission,
  recordProductOrderGroupCommissions,
  getTenantSalesTotals,
  getAllTimePlatformEarnings,
  getPlatformCommissionTotals,
  getTenantCommissionStats,
  getMonthlyCommissionByTenant,
  getCommissionHistory,
};
