-- Supabase/PostgreSQL schema for Multi-Tenant Cleaning Platform
-- Converted from backend/database/schema.sql (MySQL)

-- Keep public schema
set search_path = public;

-- Generic updated_at trigger
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists super_admin (
  id integer generated by default as identity primary key,
  email varchar(255) not null unique,
  password_hash varchar(255) not null,
  full_name varchar(255) not null,
  phone varchar(50),
  is_active boolean default true,
  last_login timestamp,
  created_at timestamp default now(),
  updated_at timestamp default now()
);

create table if not exists tenants (
  id integer generated by default as identity primary key,
  email varchar(255) not null unique,
  password_hash varchar(255) not null,
  full_name varchar(255) not null,
  phone varchar(50),
  email_verified boolean default false,
  email_verification_token varchar(255),
  email_verification_expires timestamp,
  status varchar(20) default 'pending' check (status in ('pending','approved','suspended','rejected')),
  admin_approval_token varchar(255),
  admin_approval_token_expires timestamp,
  is_active boolean default true,
  last_login timestamp,
  created_at timestamp default now(),
  updated_at timestamp default now()
);

create table if not exists companies (
  id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(id) on delete cascade,
  company_name varchar(255) not null,
  logo_url varchar(500),
  address text,
  phone varchar(50),
  email varchar(255),
  working_hours jsonb,
  license_number varchar(100),
  description text,
  latitude numeric(10,8),
  longitude numeric(11,8),
  rating numeric(3,2) default 0.00,
  total_reviews integer default 0,
  created_at timestamp default now(),
  updated_at timestamp default now()
);
create index if not exists idx_companies_tenant_id on companies(tenant_id);

create table if not exists cleaners (
  id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(id) on delete cascade,
  email varchar(255) not null,
  password_hash varchar(255) not null,
  full_name varchar(255) not null,
  phone varchar(50),
  photo_url varchar(500),
  status varchar(20) default 'active' check (status in ('active','suspended','inactive')),
  must_change_password boolean default true,
  availability jsonb,
  performance_rating numeric(3,2) default 0.00,
  total_jobs_completed integer default 0,
  is_active boolean default true,
  last_login timestamp,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  unique (tenant_id, email)
);
create index if not exists idx_cleaners_tenant_id on cleaners(tenant_id);

create table if not exists customers (
  id integer generated by default as identity primary key,
  tenant_id integer,
  email varchar(255) not null unique,
  password_hash varchar(255) not null,
  full_name varchar(255) not null,
  phone varchar(50),
  address text,
  is_blacklisted boolean default false,
  blacklist_reason text,
  is_active boolean default true,
  last_login timestamp,
  created_at timestamp default now(),
  updated_at timestamp default now()
);
create index if not exists idx_customers_tenant_id on customers(tenant_id);
create index if not exists idx_customers_email on customers(email);

create table if not exists services (
  id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(id) on delete cascade,
  name varchar(255) not null,
  description text,
  price numeric(10,2) not null,
  duration_minutes integer not null default 60,
  image_url varchar(500),
  is_active boolean default true,
  created_at timestamp default now(),
  updated_at timestamp default now()
);
create index if not exists idx_services_tenant_id on services(tenant_id);

create table if not exists booking_status (
  id integer generated by default as identity primary key,
  name varchar(50) not null unique,
  description varchar(255)
);

create table if not exists bookings (
  id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(id) on delete cascade,
  customer_id integer not null references customers(id),
  service_id integer not null references services(id),
  status_id integer not null default 1 references booking_status(id),
  scheduled_date date not null,
  scheduled_time time not null,
  address text not null,
  special_instructions text,
  total_amount numeric(10,2) not null,
  rejection_reason text,
  cancellation_reason text,
  completed_at timestamp,
  created_at timestamp default now(),
  updated_at timestamp default now()
);
create index if not exists idx_bookings_tenant_id on bookings(tenant_id);
create index if not exists idx_bookings_customer_id on bookings(customer_id);
create index if not exists idx_bookings_status_id on bookings(status_id);
create index if not exists idx_bookings_scheduled_date on bookings(scheduled_date);

create table if not exists cleaner_assignments (
  id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(id) on delete cascade,
  booking_id integer not null references bookings(id) on delete cascade,
  cleaner_id integer not null references cleaners(id),
  status varchar(20) default 'assigned' check (status in ('assigned','accepted','rejected','in_progress','completed')),
  notes text,
  completion_photo_url varchar(500),
  started_at timestamp,
  completed_at timestamp,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  unique (booking_id, cleaner_id)
);
create index if not exists idx_cleaner_assignments_tenant_id on cleaner_assignments(tenant_id);
create index if not exists idx_cleaner_assignments_cleaner_id on cleaner_assignments(cleaner_id);

create table if not exists payments (
  id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(id) on delete cascade,
  booking_id integer not null references bookings(id),
  customer_id integer not null references customers(id),
  amount numeric(10,2) not null,
  payment_method varchar(20) not null check (payment_method in ('mobile_money','card','cash','bank_transfer','flutterwave')),
  status varchar(20) default 'pending' check (status in ('pending','confirmed','successful','failed','refunded')),
  transaction_ref varchar(255),
  confirmed_at timestamp,
  confirmed_by integer,
  created_at timestamp default now(),
  updated_at timestamp default now()
);
create index if not exists idx_payments_tenant_id on payments(tenant_id);
create index if not exists idx_payments_booking_id on payments(booking_id);

create table if not exists invoices (
  id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(id) on delete cascade,
  booking_id integer not null references bookings(id),
  payment_id integer references payments(id),
  invoice_number varchar(50) not null unique,
  amount numeric(10,2) not null,
  status varchar(20) default 'draft' check (status in ('draft','sent','paid','cancelled')),
  issued_at timestamp,
  due_date date,
  created_at timestamp default now(),
  updated_at timestamp default now()
);
create index if not exists idx_invoices_tenant_id on invoices(tenant_id);

create table if not exists products (
  id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(id) on delete cascade,
  name varchar(255) not null,
  description text,
  price numeric(10,2) not null,
  image_url varchar(500),
  stock_quantity integer default 0,
  is_active boolean default true,
  created_at timestamp default now(),
  updated_at timestamp default now()
);
create index if not exists idx_products_tenant_id on products(tenant_id);

create table if not exists product_orders (
  id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(id) on delete cascade,
  product_id integer not null references products(id),
  customer_id integer not null references customers(id),
  quantity integer not null default 1,
  unit_price numeric(10,2) not null,
  total_amount numeric(10,2) not null,
  payment_method varchar(30) not null check (payment_method in ('cash_on_delivery', 'mobile_money', 'flutterwave')),
  status varchar(30) default 'placed' check (status in ('placed', 'payment_pending', 'paid', 'delivered', 'cancelled')),
  delivery_address text not null,
  delivery_phone varchar(50),
  transaction_ref varchar(255),
  notes text,
  order_group_id varchar(50),
  confirmed_at timestamp,
  confirmed_by integer,
  created_at timestamp default now(),
  updated_at timestamp default now()
);
create index if not exists idx_product_orders_tenant_id on product_orders(tenant_id);
create index if not exists idx_product_orders_customer_id on product_orders(customer_id);

create table if not exists reviews (
  id integer generated by default as identity primary key,
  tenant_id integer not null references tenants(id) on delete cascade,
  booking_id integer not null references bookings(id),
  customer_id integer not null references customers(id),
  cleaner_id integer references cleaners(id),
  company_rating integer not null check (company_rating between 1 and 5),
  cleaner_rating integer check (cleaner_rating between 1 and 5),
  comment text,
  tenant_reply text,
  is_visible boolean default true,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  unique (booking_id)
);
create index if not exists idx_reviews_tenant_id on reviews(tenant_id);

create table if not exists notifications (
  id integer generated by default as identity primary key,
  tenant_id integer,
  user_type varchar(20) not null check (user_type in ('super_admin','tenant','cleaner','customer','all')),
  user_id integer,
  title varchar(255) not null,
  message text not null,
  type varchar(20) default 'info' check (type in ('info','success','warning','error','announcement')),
  is_read boolean default false,
  link varchar(500),
  created_at timestamp default now()
);
create index if not exists idx_notifications_tenant_user on notifications(tenant_id, user_type, user_id);
create index if not exists idx_notifications_is_read on notifications(is_read);

create table if not exists activity_logs (
  id integer generated by default as identity primary key,
  tenant_id integer,
  user_type varchar(20) not null check (user_type in ('super_admin','tenant','cleaner','customer')),
  user_id integer not null,
  action varchar(100) not null,
  entity_type varchar(50),
  entity_id integer,
  details jsonb,
  ip_address varchar(45),
  created_at timestamp default now()
);
create index if not exists idx_activity_logs_tenant_id on activity_logs(tenant_id);
create index if not exists idx_activity_logs_user on activity_logs(user_type, user_id);
create index if not exists idx_activity_logs_created_at on activity_logs(created_at);

create table if not exists password_resets (
  id integer generated by default as identity primary key,
  user_type varchar(20) not null check (user_type in ('super_admin','tenant','cleaner','customer')),
  user_id integer not null,
  token varchar(255) not null unique,
  expires_at timestamp not null,
  used boolean default false,
  created_at timestamp default now()
);
create index if not exists idx_password_resets_token on password_resets(token);
create index if not exists idx_password_resets_user on password_resets(user_type, user_id);

-- Attach updated_at trigger to tables that have updated_at
drop trigger if exists trg_super_admin_updated_at on super_admin;
create trigger trg_super_admin_updated_at before update on super_admin
for each row execute function set_updated_at();

drop trigger if exists trg_tenants_updated_at on tenants;
create trigger trg_tenants_updated_at before update on tenants
for each row execute function set_updated_at();

drop trigger if exists trg_companies_updated_at on companies;
create trigger trg_companies_updated_at before update on companies
for each row execute function set_updated_at();

drop trigger if exists trg_cleaners_updated_at on cleaners;
create trigger trg_cleaners_updated_at before update on cleaners
for each row execute function set_updated_at();

drop trigger if exists trg_customers_updated_at on customers;
create trigger trg_customers_updated_at before update on customers
for each row execute function set_updated_at();

drop trigger if exists trg_services_updated_at on services;
create trigger trg_services_updated_at before update on services
for each row execute function set_updated_at();

drop trigger if exists trg_bookings_updated_at on bookings;
create trigger trg_bookings_updated_at before update on bookings
for each row execute function set_updated_at();

drop trigger if exists trg_cleaner_assignments_updated_at on cleaner_assignments;
create trigger trg_cleaner_assignments_updated_at before update on cleaner_assignments
for each row execute function set_updated_at();

drop trigger if exists trg_payments_updated_at on payments;
create trigger trg_payments_updated_at before update on payments
for each row execute function set_updated_at();

drop trigger if exists trg_invoices_updated_at on invoices;
create trigger trg_invoices_updated_at before update on invoices
for each row execute function set_updated_at();

drop trigger if exists trg_reviews_updated_at on reviews;
create trigger trg_reviews_updated_at before update on reviews
for each row execute function set_updated_at();

-- Seed booking statuses
insert into booking_status (name, description) values
  ('pending', 'Awaiting tenant approval'),
  ('accepted', 'Booking accepted by tenant'),
  ('rejected', 'Booking rejected by tenant'),
  ('assigned', 'Cleaner assigned'),
  ('in_progress', 'Cleaning in progress'),
  ('completed', 'Service completed'),
  ('cancelled', 'Booking cancelled')
on conflict (name) do update set description = excluded.description;

